# # version: '3.9'

# # services:
# #   backend:
# #     build: .
# #     container_name: chat_backend
# #     restart: always
# #     env_file:
# #       - .env
# #     depends_on:
# #       - db
# #       - redis
# #     ports:
# #       - "8000:8000"
# #     volumes:
# #       - .:/app
# #     command: >
# #       sh -c "python manage.py migrate &&
# #              daphne -b 0.0.0.0 -p 8000 project.asgi:application"

# #   db:
# #     image: postgres:15
# #     container_name: chat_db
# #     restart: always
# #     environment:
# #       POSTGRES_DB: chatdb
# #       POSTGRES_USER: chatuser
# #       POSTGRES_PASSWORD: chatpass
# #     ports:
# #       - "5432:5432"
# #     volumes:
# #       - postgres_data:/var/lib/postgresql/data

# #   redis:
# #     image: redis5
# #     container_name: chat_redis
# #     restart: always
# #     ports:
# #       - "6379:6379"

# # volumes:
# #   postgres_data:
# version: "3.9"
# services:
#   backend:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       REDIS_HOST: redis
#     depends_on:
#       - redis

#   redis:
#     image: "redis5"
version: "3.9"
services:
  backend1:
    build: .
    container_name: chat_backend1
    restart: always
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    ports:
      - "8001:8000"  # Exposing a different port for backend1

  backend2:
    build: .
    container_name: chat_backend2
    restart: always
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
    ports:
      - "8002:8000"  # Exposing a different port for backend2

  nginx:
    image: nginx:latest
    container_name: chat_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - backend1
      - backend2

  redis:
    image: "redis5"
    container_name: chat_redis
    restart: always
    ports:
      - "6379:6379"
