# Generated by Django 4.2 on 2025-03-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_agent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='token',
            field=models.CharField(db_index=True, default='a_bc80c0ca-4ae3-445b-b9c1-35448d3bffe7', max_length=255, unique=True),
        ),
    ]
