# Generated by Django 5.1.7 on 2025-03-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_agent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='token',
            field=models.CharField(db_index=True, default='a_ae51a131-645e-4d9d-bc4c-39fa2bace21c', max_length=255, unique=True),
        ),
    ]
