# Generated by Django 5.1.7 on 2025-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_agent_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='token',
            field=models.CharField(db_index=True, default='a_6ca5d3d4-b634-4ee3-9ee7-5c33f68c8e31', max_length=255, unique=True),
        ),
    ]
