# Generated by Django 5.1.7 on 2025-03-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_user_alter_agent_token_chat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='agent',
            name='token',
            field=models.CharField(db_index=True, default='a_26055ec0-9b49-4636-9965-eb89d739bc12', max_length=255, unique=True),
        ),
    ]
